name: "$(BuildDefinitionName)_$(date:yyyyMMdd)_$(rev:.r)"

trigger:
  branches:
    include: ["main"]

variables:
  - template: "build/pipeline-variables.yml"
  - group: "SSH for GitHub"

pool:
  vmImage: $(vmImageName)

stages:
  #Static code and Unit tests
  #Build
  - stage: "build"
    displayName: "Build"
    # dependsOn: "tests"
    jobs:
      - job: "bumpVersion"
        displayName: "Bump Version"
        continueOnError: false
        steps:
          - task: InstallSSHKey@0
            displayName: "Install SSH Key"
            inputs:
              knownHostEntry: "$(gitSshKnownHosts)"
              sshPublicKey: "$(gitSshPublicKey)"
              sshKeySecureFile: "$(sshKeySecureFile)"
  #Deploy

